# Generated by Django 3.2.10 on 2021-12-14 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RadioActiv8", "0005_set_default_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="RadioActiv8.session"
            ),
        ),
    ]
