# Generated by Django 4.0 on 2021-12-16 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RadioActiv8", "0007_alter_event_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
