# Generated by Django 4.0 on 2021-12-27 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("RadioActiv8", "0014_rename_location_name_radio_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patrol",
            name="gps_tracker",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="RadioActiv8.gpstracker",
            ),
        ),
    ]
