# Generated by Django 4.0 on 2021-12-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RadioActiv8", "0015_alter_patrol_gps_tracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patrol",
            name="current_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="RadioActiv8.base",
            ),
        ),
    ]
