# Generated by Django 4.0 on 2021-12-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RadioActiv8", "0016_alter_patrol_current_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="home_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="starts_session",
                to="RadioActiv8.base",
            ),
        ),
    ]
