# Generated by Django 4.0 on 2021-12-29 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("RadioActiv8", "0017_session_home_base"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="base",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="gpstracker",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="intelligence",
            options={"ordering": ["base", "question"]},
        ),
        migrations.AlterModelOptions(
            name="participant",
            options={"ordering": ["full_name"]},
        ),
        migrations.AlterModelOptions(
            name="patrol",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="radio",
            options={"ordering": ["name"]},
        ),
    ]
