# Generated by Django 4.0 on 2022-01-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RadioActiv8", "0020_alter_session_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="session",
            field=models.ManyToManyField(blank=True, to="RadioActiv8.Session"),
        ),
    ]
