# Generated by Django 4.1 on 2022-09-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioActiv8', '0021_alter_location_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrol',
            name='number_of_members',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
