# Generated by Django 4.1 on 2022-09-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioActiv8', '0022_patrol_number_of_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actual_event_time',
            field=models.DateTimeField(null=True, verbose_name='Reported event time'),
        ),
    ]
