# Generated by Django 5.0.2 on 2024-04-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RadioActiv8", "0025_remove_historicalpatrol_member_class_and_more"),
        ("scoutsvic_ems", "0022_missionassignment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patrol",
            options={"ordering": ["event_patrol__name"]},
        ),
        migrations.RenameField(
            model_name="historicalpatrol",
            old_name="name",
            new_name="_old_name",
        ),
        migrations.RenameField(
            model_name="historicalpatrol",
            old_name="number_of_members",
            new_name="_old_number_of_members",
        ),
        migrations.RenameField(
            model_name="historicalpatrol",
            old_name="project_patrol",
            new_name="_old_project_patrol",
        ),
        migrations.RenameField(
            model_name="patrol",
            old_name="member_classes",
            new_name="_old_member_classes",
        ),
        migrations.RenameField(
            model_name="patrol",
            old_name="name",
            new_name="_old_name",
        ),
        migrations.RenameField(
            model_name="patrol",
            old_name="number_of_members",
            new_name="_old_number_of_members",
        ),
        migrations.RenameField(
            model_name="patrol",
            old_name="preferred_bases",
            new_name="_old_preferred_bases",
        ),
        migrations.RenameField(
            model_name="patrol",
            old_name="project_patrol",
            new_name="_old_project_patrol",
        ),
        migrations.AddField(
            model_name="historicalpatrol",
            name="event_patrol",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="scoutsvic_ems.eventpatrol",
            ),
        ),
        migrations.AddField(
            model_name="patrol",
            name="event_patrol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scoutsvic_ems.eventpatrol",
            ),
        ),
    ]
