# Generated by Django 5.0.2 on 2024-03-09 02:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "RadioActiv8",
            "0023_patrol_preferred_bases",
        ),
        ("RadioActiv8", "0025_remove_historicalpatrol_member_class_and_more"),
    ]

    operations = []
