# Generated by Django 5.0.2 on 2024-04-26 09:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RadioActiv8", "0023_patrol_preferred_bases"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalBaseRoutePair",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("route", models.JSONField(blank=True, null=True)),
                ("length", models.IntegerField()),
                ("time", models.DurationField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="RadioActiv8.base",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="RadioActiv8.base",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical base route pair",
                "verbose_name_plural": "historical base route pairs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="BaseRoutePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route", models.JSONField(blank=True, null=True)),
                ("length", models.IntegerField()),
                ("time", models.DurationField()),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_from",
                        to="RadioActiv8.base",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_to",
                        to="RadioActiv8.base",
                    ),
                ),
            ],
            options={
                "ordering": ["source", "time"],
                "indexes": [
                    models.Index(
                        fields=["source", "time"], name="RadioActiv8_source__ed48af_idx"
                    ),
                    models.Index(
                        fields=["source", "length"],
                        name="RadioActiv8_source__335811_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="baseroutepair",
            constraint=models.UniqueConstraint(
                fields=("source", "destination"), name="one_instance_per_base_pair"
            ),
        ),
    ]
