# Generated by Django 5.0.2 on 2024-03-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RadioActiv8", "0022_patrol_number_of_members"),
        ("RadioActiv8", "0026_merge_20240309_1340"),
    ]

    operations = []
