# Generated by Django 5.0.2 on 2024-03-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RadioActiv8", "0027_merge_20240309_1352"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatrol",
            name="number_of_members",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
