# Generated by Django 3.2.3 on 2021-05-13 14:38

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gps_location', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(144.6376, -36.49197), srid=4326)),
                ('min_patrols', models.IntegerField(blank=True)),
                ('max_patrols', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gps_location', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(144.6376, -36.49197), srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(unique=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RadioActiv8.base')),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RadioActiv8.patrol')),
            ],
        ),
        migrations.CreateModel(
            name='Intelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('answer', models.CharField(max_length=1024)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RadioActiv8.base')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('check_out', models.BooleanField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RadioActiv8.base')),
                ('intelligence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RadioActiv8.intelligence')),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RadioActiv8.patrol')),
            ],
        ),
    ]
