# Generated by Django 3.2.3 on 2021-05-14 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RadioActiv8', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='intelligence',
        ),
        migrations.AddField(
            model_name='patrol',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RadioActiv8.base'),
        ),
        migrations.AlterField(
            model_name='event',
            name='check_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PatrolAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intelligence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RadioActiv8.intelligence')),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RadioActiv8.patrol')),
            ],
        ),
    ]
