# Generated by Django 3.2.3 on 2021-05-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioActiv8', '0003_auto_20210523_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='activity_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('R',
                     'Reading data'),
                    ('S',
                     'Self-directed'),
                    ('F',
                     'Facilitated')],
                default='S',
                max_length=1),
        ),
        migrations.AlterField(
            model_name='base',
            name='max_patrols',
            field=models.IntegerField(
                blank=True,
                null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='min_patrols',
            field=models.IntegerField(
                blank=True,
                null=True),
        ),
    ]
