# Generated by Django 3.2.10 on 2021-12-13 01:56

from django.db import migrations

def set_default_session(apps, schema_editor):
    Session = apps.get_model("RadioActiv8", "Session")
    Location = apps.get_model("RadioActiv8", "Location")
    Patrol = apps.get_model("RadioActiv8", "Patrol")
    Event = apps.get_model("RadioActiv8", "Event")
    db_alias = schema_editor.connection.alias

    default_session = Session.objects.using(db_alias).get(name='DEFAULT SESSION')

    for l in Location.objects.filter(session=None):
        l.session.add(default_session)

    for p in Patrol.objects.filter(session=None):
        p.session.add(default_session)

    Event.objects.filter(session=None).update(session=default_session)


def unset_default_session(apps, schema_editor):
    Session = apps.get_model("RadioActiv8", "Session")
    Location = apps.get_model("RadioActiv8", "Location")
    Patrol = apps.get_model("RadioActiv8", "Patrol")
    Event = apps.get_model("RadioActiv8", "Event")
    db_alias = schema_editor.connection.alias

    default_session = Session.objects.using(db_alias).get(name='DEFAULT SESSION')

    for l in Location.objects.filter(session=default_session):
        l.session.remove(default_session)

    for p in Patrol.objects.filter(session=default_session):
        p.session.remove(default_session)

    Event.objects.filter(session=default_session).update(session=None)
    

class Migration(migrations.Migration):

    dependencies = [
        ('RadioActiv8', '0004_create_default_session'),
    ]

    operations = [
        migrations.RunPython(set_default_session, unset_default_session),
    ]
