# Generated by Django 3.2.3 on 2021-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioActiv8', '0004_auto_20210528_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
