# Generated by Django 4.0 on 2022-01-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RadioActiv8', '0019_alter_session_home_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start_time', 'name']},
        ),
    ]
